/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program_Latihan_3;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Shendi Rakhma Diansyah
 */
public class Program_Latihan_3_2 extends javax.swing.JFrame {

    /**
     * Creates new form Program_Latihan_3_2
     */
    public Program_Latihan_3_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textjudul = new javax.swing.JLabel();
        texthuruf = new javax.swing.JLabel();
        textukuran = new javax.swing.JLabel();
        textwarna = new javax.swing.JLabel();
        cbhuruf = new javax.swing.JComboBox();
        cbukuran = new javax.swing.JComboBox();
        cbwarna = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textjudul.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textjudul.setText("PEROGRAM LATIHAN 3.2");

        texthuruf.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        texthuruf.setText("Jenis Font");

        textukuran.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textukuran.setText("Ukuran");

        textwarna.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textwarna.setText("Warna");

        cbhuruf.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbhuruf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Verdana", "Tahoma" }));
        cbhuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhurufActionPerformed(evt);
            }
        });

        cbukuran.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbukuran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "14", "16", "18" }));
        cbukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbukuranActionPerformed(evt);
            }
        });

        cbwarna.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbwarna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Merah", "Hijau", "Biru" }));
        cbwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbwarnaActionPerformed(evt);
            }
        });

        textoutput.setColumns(20);
        textoutput.setLineWrap(true);
        textoutput.setRows(5);
        jScrollPane1.setViewportView(textoutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texthuruf)
                            .addComponent(textukuran)
                            .addComponent(textwarna))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbhuruf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbwarna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(textjudul)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textjudul)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texthuruf)
                            .addComponent(cbhuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textukuran))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textwarna)
                            .addComponent(cbwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbhurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhurufActionPerformed
        // TODO add your handling code here:
        if(cbhuruf.getSelectedItem()=="Arial")
        {
            textoutput.setFont(new Font("Arial",Font.PLAIN,12));
        }
        else if(cbhuruf.getSelectedItem()=="Verdana")
        {
            textoutput.setFont(new Font("Verdana",Font.PLAIN,12));
        }
        else if(cbhuruf.getSelectedItem()=="Tahoma")
        {
            textoutput.setFont(new Font("Tahoma",Font.PLAIN,12));
        }
    }//GEN-LAST:event_cbhurufActionPerformed

    private void cbukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbukuranActionPerformed
        // TODO add your handling code here:
        if(cbukuran.getSelectedItem()=="14")
        {
            textoutput.setFont(new Font(textoutput.getFont().getName(),textoutput.getFont().getStyle(),14));
        }
        else if(cbukuran.getSelectedItem()=="16")
        {
            textoutput.setFont(new Font(textoutput.getFont().getName(),textoutput.getFont().getStyle(),16));
        }
        else if(cbukuran.getSelectedItem()=="18")
        {
            textoutput.setFont(new Font(textoutput.getFont().getName(),textoutput.getFont().getStyle(),18));
        }
            
    }//GEN-LAST:event_cbukuranActionPerformed

    private void cbwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbwarnaActionPerformed
        // TODO add your handling code here:
        if(cbwarna.getSelectedItem()=="Merah")
        {
            textoutput.setForeground(Color.red);
        }
        else if(cbwarna.getSelectedItem()=="Hijau")
        {
            textoutput.setForeground(Color.green);
        }
        else if(cbwarna.getSelectedItem()=="Biru")
        {
            textoutput.setForeground(Color.blue);
        }
    }//GEN-LAST:event_cbwarnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program_Latihan_3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program_Latihan_3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program_Latihan_3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_Latihan_3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program_Latihan_3_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbhuruf;
    private javax.swing.JComboBox cbukuran;
    private javax.swing.JComboBox cbwarna;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel texthuruf;
    private javax.swing.JLabel textjudul;
    private javax.swing.JTextArea textoutput;
    private javax.swing.JLabel textukuran;
    private javax.swing.JLabel textwarna;
    // End of variables declaration//GEN-END:variables
}
